package beans;
// Generated May 4, 2017 2:42:21 PM by Hibernate Tools 4.3.1



/**
 * Notes generated by hbm2java
 */
public class Notes  implements java.io.Serializable {


     private NotesId id;

    public Notes() {
    }

    public Notes(NotesId id) {
       this.id = id;
    }
   
    public NotesId getId() {
        return this.id;
    }
    
    public void setId(NotesId id) {
        this.id = id;
    }




}


