package beans;
// Generated May 4, 2017 2:42:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * NotesId generated by hbm2java
 */
public class NotesId  implements java.io.Serializable {


     private String username;
     private BigDecimal tripid;
     private String note;

    public NotesId() {
    }

    public NotesId(String username, BigDecimal tripid, String note) {
       this.username = username;
       this.tripid = tripid;
       this.note = note;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public BigDecimal getTripid() {
        return this.tripid;
    }
    
    public void setTripid(BigDecimal tripid) {
        this.tripid = tripid;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotesId) ) return false;
		 NotesId castOther = ( NotesId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getTripid()==castOther.getTripid()) || ( this.getTripid()!=null && castOther.getTripid()!=null && this.getTripid().equals(castOther.getTripid()) ) )
 && ( (this.getNote()==castOther.getNote()) || ( this.getNote()!=null && castOther.getNote()!=null && this.getNote().equals(castOther.getNote()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getTripid() == null ? 0 : this.getTripid().hashCode() );
         result = 37 * result + ( getNote() == null ? 0 : this.getNote().hashCode() );
         return result;
   }   


}


