package beans;
// Generated May 4, 2017 2:42:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TripsId generated by hbm2java
 */
public class TripsId  implements java.io.Serializable {


     private BigDecimal tripId;
     private String username;

    public TripsId() {
    }

    public TripsId(BigDecimal tripId, String username) {
       this.tripId = tripId;
       this.username = username;
    }
   
    public BigDecimal getTripId() {
        return this.tripId;
    }
    
    public void setTripId(BigDecimal tripId) {
        this.tripId = tripId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TripsId) ) return false;
		 TripsId castOther = ( TripsId ) other; 
         
		 return ( (this.getTripId()==castOther.getTripId()) || ( this.getTripId()!=null && castOther.getTripId()!=null && this.getTripId().equals(castOther.getTripId()) ) )
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTripId() == null ? 0 : this.getTripId().hashCode() );
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


