package beans;
// Generated May 4, 2017 2:42:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Trips generated by hbm2java
 */
public class Trips  implements java.io.Serializable {


     private TripsId id;
     private String tripName;
     private String startPoint;
     private String endPoint;
     private BigDecimal startTime;
     private BigDecimal endTime;
     private BigDecimal status;
     private BigDecimal status2;
     private BigDecimal SLat;
     private BigDecimal SLonge;
     private BigDecimal FLat;
     private BigDecimal FLonge;

    public Trips() {
    }

	
    public Trips(TripsId id) {
        this.id = id;
    }
    public Trips(TripsId id, String tripName, String startPoint, String endPoint, BigDecimal startTime, BigDecimal endTime, BigDecimal status, BigDecimal status2, BigDecimal SLat, BigDecimal SLonge, BigDecimal FLat, BigDecimal FLonge) {
       this.id = id;
       this.tripName = tripName;
       this.startPoint = startPoint;
       this.endPoint = endPoint;
       this.startTime = startTime;
       this.endTime = endTime;
       this.status = status;
       this.status2 = status2;
       this.SLat = SLat;
       this.SLonge = SLonge;
       this.FLat = FLat;
       this.FLonge = FLonge;
    }
   
    public TripsId getId() {
        return this.id;
    }
    
    public void setId(TripsId id) {
        this.id = id;
    }
    public String getTripName() {
        return this.tripName;
    }
    
    public void setTripName(String tripName) {
        this.tripName = tripName;
    }
    public String getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint;
    }
    public String getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }
    public BigDecimal getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(BigDecimal startTime) {
        this.startTime = startTime;
    }
    public BigDecimal getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(BigDecimal endTime) {
        this.endTime = endTime;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getStatus2() {
        return this.status2;
    }
    
    public void setStatus2(BigDecimal status2) {
        this.status2 = status2;
    }
    public BigDecimal getSLat() {
        return this.SLat;
    }
    
    public void setSLat(BigDecimal SLat) {
        this.SLat = SLat;
    }
    public BigDecimal getSLonge() {
        return this.SLonge;
    }
    
    public void setSLonge(BigDecimal SLonge) {
        this.SLonge = SLonge;
    }
    public BigDecimal getFLat() {
        return this.FLat;
    }
    
    public void setFLat(BigDecimal FLat) {
        this.FLat = FLat;
    }
    public BigDecimal getFLonge() {
        return this.FLonge;
    }
    
    public void setFLonge(BigDecimal FLonge) {
        this.FLonge = FLonge;
    }




}


