package beans;
// Generated May 4, 2017 2:42:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String password;
     private BigDecimal type;

    public Users() {
    }

	
    public Users(String username) {
        this.username = username;
    }
    public Users(String username, String password, BigDecimal type) {
       this.username = username;
       this.password = password;
       this.type = type;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }




}


