package bean;
// Generated May 20, 2017 1:55:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Answer generated by hbm2java
 */
public class Answer  implements java.io.Serializable {


     private int answerId;
     private Integer questionId;
     private Serializable answerPhotoPath;
     private Serializable answerBody;
     private Boolean answerCorrect;

    public Answer() {
    }

	
    public Answer(int answerId) {
        this.answerId = answerId;
    }
    public Answer(int answerId, Integer questionId, Serializable answerPhotoPath, Serializable answerBody, Boolean answerCorrect) {
       this.answerId = answerId;
       this.questionId = questionId;
       this.answerPhotoPath = answerPhotoPath;
       this.answerBody = answerBody;
       this.answerCorrect = answerCorrect;
    }
   
    public int getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public Serializable getAnswerPhotoPath() {
        return this.answerPhotoPath;
    }
    
    public void setAnswerPhotoPath(Serializable answerPhotoPath) {
        this.answerPhotoPath = answerPhotoPath;
    }
    public Serializable getAnswerBody() {
        return this.answerBody;
    }
    
    public void setAnswerBody(Serializable answerBody) {
        this.answerBody = answerBody;
    }
    public Boolean getAnswerCorrect() {
        return this.answerCorrect;
    }
    
    public void setAnswerCorrect(Boolean answerCorrect) {
        this.answerCorrect = answerCorrect;
    }




}


