package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private int branchId;
     private Serializable branchName;
     private Serializable arabicname;
     private String msreplTranVersion;
     private Integer trainbranchid;
     private Set platfromIntakes = new HashSet(0);

    public Branch() {
    }

	
    public Branch(int branchId, String msreplTranVersion) {
        this.branchId = branchId;
        this.msreplTranVersion = msreplTranVersion;
    }
    public Branch(int branchId, Serializable branchName, Serializable arabicname, String msreplTranVersion, Integer trainbranchid, Set platfromIntakes) {
       this.branchId = branchId;
       this.branchName = branchName;
       this.arabicname = arabicname;
       this.msreplTranVersion = msreplTranVersion;
       this.trainbranchid = trainbranchid;
       this.platfromIntakes = platfromIntakes;
    }
   
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }
    public Serializable getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(Serializable branchName) {
        this.branchName = branchName;
    }
    public Serializable getArabicname() {
        return this.arabicname;
    }
    
    public void setArabicname(Serializable arabicname) {
        this.arabicname = arabicname;
    }
    public String getMsreplTranVersion() {
        return this.msreplTranVersion;
    }
    
    public void setMsreplTranVersion(String msreplTranVersion) {
        this.msreplTranVersion = msreplTranVersion;
    }
    public Integer getTrainbranchid() {
        return this.trainbranchid;
    }
    
    public void setTrainbranchid(Integer trainbranchid) {
        this.trainbranchid = trainbranchid;
    }
  
    public Set getPlatfromIntakes() {
        return this.platfromIntakes;
    }
    
    public void setPlatfromIntakes(Set platfromIntakes) {
        this.platfromIntakes = platfromIntakes;
    }




}


