package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CourseManual generated by hbm2java
 */
public class CourseManual  implements java.io.Serializable {


     private int courseManualId;
     private Course course;
     private Integer totalGrade;
     private Integer minGrade;
     private Integer labsNumber;
     private Integer lecturesNumber;
     private Integer lech;
     private Integer selfh;
     private Integer labh;
     private Integer credit;
     private Serializable coursenote;
     private Serializable swReq;
     private Serializable hwReq;
     private Serializable courseCode;
     private Serializable courseDescription;
     private Serializable courseObjective;
     private Serializable courseContent;
     private Integer programIntakeId;
     private Set trackManuals = new HashSet(0);

    public CourseManual() {
    }

	
    public CourseManual(int courseManualId) {
        this.courseManualId = courseManualId;
    }
    public CourseManual(int courseManualId, Course course, Integer totalGrade, Integer minGrade, Integer labsNumber, Integer lecturesNumber, Integer lech, Integer selfh, Integer labh, Integer credit, Serializable coursenote, Serializable swReq, Serializable hwReq, Serializable courseCode, Serializable courseDescription, Serializable courseObjective, Serializable courseContent, Integer programIntakeId, Set trackManuals) {
       this.courseManualId = courseManualId;
       this.course = course;
       this.totalGrade = totalGrade;
       this.minGrade = minGrade;
       this.labsNumber = labsNumber;
       this.lecturesNumber = lecturesNumber;
       this.lech = lech;
       this.selfh = selfh;
       this.labh = labh;
       this.credit = credit;
       this.coursenote = coursenote;
       this.swReq = swReq;
       this.hwReq = hwReq;
       this.courseCode = courseCode;
       this.courseDescription = courseDescription;
       this.courseObjective = courseObjective;
       this.courseContent = courseContent;
       this.programIntakeId = programIntakeId;
       this.trackManuals = trackManuals;
    }
   
    public int getCourseManualId() {
        return this.courseManualId;
    }
    
    public void setCourseManualId(int courseManualId) {
        this.courseManualId = courseManualId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Integer getTotalGrade() {
        return this.totalGrade;
    }
    
    public void setTotalGrade(Integer totalGrade) {
        this.totalGrade = totalGrade;
    }
    public Integer getMinGrade() {
        return this.minGrade;
    }
    
    public void setMinGrade(Integer minGrade) {
        this.minGrade = minGrade;
    }
    public Integer getLabsNumber() {
        return this.labsNumber;
    }
    
    public void setLabsNumber(Integer labsNumber) {
        this.labsNumber = labsNumber;
    }
    public Integer getLecturesNumber() {
        return this.lecturesNumber;
    }
    
    public void setLecturesNumber(Integer lecturesNumber) {
        this.lecturesNumber = lecturesNumber;
    }
    public Integer getLech() {
        return this.lech;
    }
    
    public void setLech(Integer lech) {
        this.lech = lech;
    }
    public Integer getSelfh() {
        return this.selfh;
    }
    
    public void setSelfh(Integer selfh) {
        this.selfh = selfh;
    }
    public Integer getLabh() {
        return this.labh;
    }
    
    public void setLabh(Integer labh) {
        this.labh = labh;
    }
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
    public Serializable getCoursenote() {
        return this.coursenote;
    }
    
    public void setCoursenote(Serializable coursenote) {
        this.coursenote = coursenote;
    }
    public Serializable getSwReq() {
        return this.swReq;
    }
    
    public void setSwReq(Serializable swReq) {
        this.swReq = swReq;
    }
    public Serializable getHwReq() {
        return this.hwReq;
    }
    
    public void setHwReq(Serializable hwReq) {
        this.hwReq = hwReq;
    }
    public Serializable getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(Serializable courseCode) {
        this.courseCode = courseCode;
    }
    public Serializable getCourseDescription() {
        return this.courseDescription;
    }
    
    public void setCourseDescription(Serializable courseDescription) {
        this.courseDescription = courseDescription;
    }
    public Serializable getCourseObjective() {
        return this.courseObjective;
    }
    
    public void setCourseObjective(Serializable courseObjective) {
        this.courseObjective = courseObjective;
    }
    public Serializable getCourseContent() {
        return this.courseContent;
    }
    
    public void setCourseContent(Serializable courseContent) {
        this.courseContent = courseContent;
    }
    public Integer getProgramIntakeId() {
        return this.programIntakeId;
    }
    
    public void setProgramIntakeId(Integer programIntakeId) {
        this.programIntakeId = programIntakeId;
    }
    public Set getTrackManuals() {
        return this.trackManuals;
    }
    
    public void setTrackManuals(Set trackManuals) {
        this.trackManuals = trackManuals;
    }




}


