package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CourseCategory generated by hbm2java
 */
public class CourseCategory  implements java.io.Serializable {


     private int categoryId;
     private Serializable categoryName;
     private String msreplTranVersion;
     private Integer order;
     private Set courses = new HashSet(0);

    public CourseCategory() {
    }

	
    public CourseCategory(int categoryId, String msreplTranVersion) {
        this.categoryId = categoryId;
        this.msreplTranVersion = msreplTranVersion;
    }
    public CourseCategory(int categoryId, Serializable categoryName, String msreplTranVersion, Integer order, Set courses) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.msreplTranVersion = msreplTranVersion;
       this.order = order;
       this.courses = courses;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public Serializable getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(Serializable categoryName) {
        this.categoryName = categoryName;
    }
    public String getMsreplTranVersion() {
        return this.msreplTranVersion;
    }
    
    public void setMsreplTranVersion(String msreplTranVersion) {
        this.msreplTranVersion = msreplTranVersion;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


