package bean;
// Generated May 22, 2017 6:14:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventId generated by hbm2java
 */
public class EventId  implements java.io.Serializable {


     private int eventId;
     private String title;
     private String description;
     private Date eventStart;
     private Date eventEnd;

    public EventId() {
    }

	
    public EventId(int eventId) {
        this.eventId = eventId;
    }
    public EventId(int eventId, String title, String description, Date eventStart, Date eventEnd) {
       this.eventId = eventId;
       this.title = title;
       this.description = description;
       this.eventStart = eventStart;
       this.eventEnd = eventEnd;
    }
   
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getEventStart() {
        return this.eventStart;
    }
    
    public void setEventStart(Date eventStart) {
        this.eventStart = eventStart;
    }
    public Date getEventEnd() {
        return this.eventEnd;
    }
    
    public void setEventEnd(Date eventEnd) {
        this.eventEnd = eventEnd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventId) ) return false;
		 EventId castOther = ( EventId ) other; 
         
		 return (this.getEventId()==castOther.getEventId())
 && ( (this.getTitle()==castOther.getTitle()) || ( this.getTitle()!=null && castOther.getTitle()!=null && this.getTitle().equals(castOther.getTitle()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getEventStart()==castOther.getEventStart()) || ( this.getEventStart()!=null && castOther.getEventStart()!=null && this.getEventStart().equals(castOther.getEventStart()) ) )
 && ( (this.getEventEnd()==castOther.getEventEnd()) || ( this.getEventEnd()!=null && castOther.getEventEnd()!=null && this.getEventEnd().equals(castOther.getEventEnd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventId();
         result = 37 * result + ( getTitle() == null ? 0 : this.getTitle().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getEventStart() == null ? 0 : this.getEventStart().hashCode() );
         result = 37 * result + ( getEventEnd() == null ? 0 : this.getEventEnd().hashCode() );
         return result;
   }   


}


