package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Intake generated by hbm2java
 */
public class Intake  implements java.io.Serializable {


     private int intakeId;
     private Integer intakeNo;
     private Date startDate;
     private Date endDate;
     private Serializable intakeName;
     private String msreplTranVersion;

    public Intake() {
    }

	
    public Intake(int intakeId, String msreplTranVersion) {
        this.intakeId = intakeId;
        this.msreplTranVersion = msreplTranVersion;
    }
    public Intake(int intakeId, Integer intakeNo, Date startDate, Date endDate, Serializable intakeName, String msreplTranVersion) {
       this.intakeId = intakeId;
       this.intakeNo = intakeNo;
       this.startDate = startDate;
       this.endDate = endDate;
       this.intakeName = intakeName;
       this.msreplTranVersion = msreplTranVersion;
    }
   
    public int getIntakeId() {
        return this.intakeId;
    }
    
    public void setIntakeId(int intakeId) {
        this.intakeId = intakeId;
    }
    public Integer getIntakeNo() {
        return this.intakeNo;
    }
    
    public void setIntakeNo(Integer intakeNo) {
        this.intakeNo = intakeNo;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Serializable getIntakeName() {
        return this.intakeName;
    }
    
    public void setIntakeName(Serializable intakeName) {
        this.intakeName = intakeName;
    }
    public String getMsreplTranVersion() {
        return this.msreplTranVersion;
    }
    
    public void setMsreplTranVersion(String msreplTranVersion) {
        this.msreplTranVersion = msreplTranVersion;
    }




}


