package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PlatfromIntake generated by hbm2java
 */
public class PlatfromIntake  implements java.io.Serializable {


     private int platformIntakeId;
     private Branch branch;
     private Platform platform;
     private ProgramIntake programIntake;
     private SubTrack subTrack;
     private Serializable graduateProfile;
     
     private Set studentBasicDatas = new HashSet(0);
     private Set trackManuals = new HashSet(0);

    public PlatfromIntake() {
    }

	
    public PlatfromIntake(int platformIntakeId) {
        this.platformIntakeId = platformIntakeId;
    }
    public PlatfromIntake(int platformIntakeId, Branch branch, Platform platform, ProgramIntake programIntake, SubTrack subTrack, Serializable graduateProfile, Set studentBasicDatas, Set trackManuals) {
       this.platformIntakeId = platformIntakeId;
       this.branch = branch;
       this.platform = platform;
       this.programIntake = programIntake;
       this.subTrack = subTrack;
       this.graduateProfile = graduateProfile;
       this.studentBasicDatas = studentBasicDatas;
       this.trackManuals = trackManuals;
    }
   
    public int getPlatformIntakeId() {
        return this.platformIntakeId;
    }
    
    public void setPlatformIntakeId(int platformIntakeId) {
        this.platformIntakeId = platformIntakeId;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Platform getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(Platform platform) {
        this.platform = platform;
    }
    public ProgramIntake getProgramIntake() {
        return this.programIntake;
    }
    
    public void setProgramIntake(ProgramIntake programIntake) {
        this.programIntake = programIntake;
    }
    public SubTrack getSubTrack() {
        return this.subTrack;
    }
    
    public void setSubTrack(SubTrack subTrack) {
        this.subTrack = subTrack;
    }
    public Serializable getGraduateProfile() {
        return this.graduateProfile;
    }
    
    public void setGraduateProfile(Serializable graduateProfile) {
        this.graduateProfile = graduateProfile;
    }
    public Set getStudentBasicDatas() {
        return this.studentBasicDatas;
    }
    
    public void setStudentBasicDatas(Set studentBasicDatas) {
        this.studentBasicDatas = studentBasicDatas;
    }
    public Set getTrackManuals() {
        return this.trackManuals;
    }
    
    public void setTrackManuals(Set trackManuals) {
        this.trackManuals = trackManuals;
    }




}


