package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Platform generated by hbm2java
 */
public class Platform  implements java.io.Serializable {


     private int platformId;
     private Serializable platformName;
     private Serializable nameAr;
     private Integer departmentId;
     private Integer higherdept;
     private String msreplTranVersion;
     private Boolean ismonthPlat;
     private Integer ownerEmployeeId;
     private Set platfromIntakes = new HashSet(0);

    public Platform() {
    }

	
    public Platform(int platformId, String msreplTranVersion) {
        this.platformId = platformId;
        this.msreplTranVersion = msreplTranVersion;
    }
    public Platform(int platformId, Serializable platformName, Serializable nameAr, Integer departmentId, Integer higherdept, String msreplTranVersion, Boolean ismonthPlat, Integer ownerEmployeeId, Set platfromIntakes) {
       this.platformId = platformId;
       this.platformName = platformName;
       this.nameAr = nameAr;
       this.departmentId = departmentId;
       this.higherdept = higherdept;
       this.msreplTranVersion = msreplTranVersion;
       this.ismonthPlat = ismonthPlat;
       this.ownerEmployeeId = ownerEmployeeId;
       this.platfromIntakes = platfromIntakes;
    }
   
    public int getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(int platformId) {
        this.platformId = platformId;
    }
    public Serializable getPlatformName() {
        return this.platformName;
    }
    
    public void setPlatformName(Serializable platformName) {
        this.platformName = platformName;
    }
    public Serializable getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(Serializable nameAr) {
        this.nameAr = nameAr;
    }
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
    public Integer getHigherdept() {
        return this.higherdept;
    }
    
    public void setHigherdept(Integer higherdept) {
        this.higherdept = higherdept;
    }
    public String getMsreplTranVersion() {
        return this.msreplTranVersion;
    }
    
    public void setMsreplTranVersion(String msreplTranVersion) {
        this.msreplTranVersion = msreplTranVersion;
    }
    public Boolean getIsmonthPlat() {
        return this.ismonthPlat;
    }
    
    public void setIsmonthPlat(Boolean ismonthPlat) {
        this.ismonthPlat = ismonthPlat;
    }
    public Integer getOwnerEmployeeId() {
        return this.ownerEmployeeId;
    }
    
    public void setOwnerEmployeeId(Integer ownerEmployeeId) {
        this.ownerEmployeeId = ownerEmployeeId;
    }
    public Set getPlatfromIntakes() {
        return this.platfromIntakes;
    }
    
    public void setPlatfromIntakes(Set platfromIntakes) {
        this.platfromIntakes = platfromIntakes;
    }




}


