package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProgramIntake generated by hbm2java
 */
public class ProgramIntake  implements java.io.Serializable {


     private int programIntakeId;
     private Programs programs;
     private int intakeId;
     private Set platfromIntakes = new HashSet(0);

    public ProgramIntake() {
    }

	
    public ProgramIntake(int programIntakeId, Programs programs, int intakeId) {
        this.programIntakeId = programIntakeId;
        this.programs = programs;
        this.intakeId = intakeId;
    }
    public ProgramIntake(int programIntakeId, Programs programs, int intakeId, Set platfromIntakes) {
       this.programIntakeId = programIntakeId;
       this.programs = programs;
       this.intakeId = intakeId;
       this.platfromIntakes = platfromIntakes;
    }
   
    public int getProgramIntakeId() {
        return this.programIntakeId;
    }
    
    public void setProgramIntakeId(int programIntakeId) {
        this.programIntakeId = programIntakeId;
    }
    public Programs getPrograms() {
        return this.programs;
    }
    
    public void setPrograms(Programs programs) {
        this.programs = programs;
    }
    public int getIntakeId() {
        return this.intakeId;
    }
    
    public void setIntakeId(int intakeId) {
        this.intakeId = intakeId;
    }
    public Set getPlatfromIntakes() {
        return this.platfromIntakes;
    }
    
    public void setPlatfromIntakes(Set platfromIntakes) {
        this.platfromIntakes = platfromIntakes;
    }




}


