package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Programs generated by hbm2java
 */
public class Programs  implements java.io.Serializable {


     private int programId;
     private Serializable programName;
     private Serializable programnotes;
     private Set programIntakes = new HashSet(0);

    public Programs() {
    }

	
    public Programs(int programId) {
        this.programId = programId;
    }
    public Programs(int programId, Serializable programName, Serializable programnotes, Set programIntakes) {
       this.programId = programId;
       this.programName = programName;
       this.programnotes = programnotes;
       this.programIntakes = programIntakes;
    }
   
    public int getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(int programId) {
        this.programId = programId;
    }
    public Serializable getProgramName() {
        return this.programName;
    }
    
    public void setProgramName(Serializable programName) {
        this.programName = programName;
    }
    public Serializable getProgramnotes() {
        return this.programnotes;
    }
    
    public void setProgramnotes(Serializable programnotes) {
        this.programnotes = programnotes;
    }
    public Set getProgramIntakes() {
        return this.programIntakes;
    }
    
    public void setProgramIntakes(Set programIntakes) {
        this.programIntakes = programIntakes;
    }




}


