package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.Date;

/**
 * StudentBasicData generated by hbm2java
 */
public class StudentBasicData  implements java.io.Serializable {


     private int studentId;
//     @JsonIgnore
     private   PlatfromIntake platfromIntake;
     private Serializable englishname;
     private Serializable arabicname;
     private Serializable applicationNo;
     private Integer fkUniversityFacultySpecializationId;
     private Integer fkFacultyId;
     private Integer fkSpecializationId;
     private Integer fkGraduationGradeId;
     private Serializable graduationYear;
     private Serializable phone;
     private Serializable mobile;
     private Serializable email;
     private Serializable barcode;
     private Integer accFlag;
     private Serializable username;
     private Serializable userpwd;
     private Serializable imagepath;
     private Serializable rejectReason;
     private Date dateOb;
     private Serializable gender;
     private Serializable address;
     private Serializable idno;
     private Serializable graduationGrade;
     private Integer rank;
     private Integer marital;
     private Integer military;
     private Integer language;
     private Serializable socialAccount;
     private Serializable school;
     private Serializable gradProjIdea;
     private Serializable projGrade;
     private Serializable certAqui;
     private Serializable postGradStud;
     private Serializable acadimicInst;
     private Serializable cvpath;
     private Serializable schoolName;
     private Serializable comment;

    public StudentBasicData() {
    }

	
    public StudentBasicData(int studentId, PlatfromIntake platfromIntake) {
        this.studentId = studentId;
        this.platfromIntake = platfromIntake;
    }
    public StudentBasicData(int studentId, PlatfromIntake platfromIntake, Serializable englishname, Serializable arabicname, Serializable applicationNo, Integer fkUniversityFacultySpecializationId, Integer fkFacultyId, Integer fkSpecializationId, Integer fkGraduationGradeId, Serializable graduationYear, Serializable phone, Serializable mobile, Serializable email, Serializable barcode, Integer accFlag, Serializable username, Serializable userpwd, Serializable imagepath, Serializable rejectReason, Date dateOb, Serializable gender, Serializable address, Serializable idno, Serializable graduationGrade, Integer rank, Integer marital, Integer military, Integer language, Serializable socialAccount, Serializable school, Serializable gradProjIdea, Serializable projGrade, Serializable certAqui, Serializable postGradStud, Serializable acadimicInst, Serializable cvpath, Serializable schoolName, Serializable comment) {
       this.studentId = studentId;
       this.platfromIntake = platfromIntake;
       this.englishname = englishname;
       this.arabicname = arabicname;
       this.applicationNo = applicationNo;
       this.fkUniversityFacultySpecializationId = fkUniversityFacultySpecializationId;
       this.fkFacultyId = fkFacultyId;
       this.fkSpecializationId = fkSpecializationId;
       this.fkGraduationGradeId = fkGraduationGradeId;
       this.graduationYear = graduationYear;
       this.phone = phone;
       this.mobile = mobile;
       this.email = email;
       this.barcode = barcode;
       this.accFlag = accFlag;
       this.username = username;
       this.userpwd = userpwd;
       this.imagepath = imagepath;
       this.rejectReason = rejectReason;
       this.dateOb = dateOb;
       this.gender = gender;
       this.address = address;
       this.idno = idno;
       this.graduationGrade = graduationGrade;
       this.rank = rank;
       this.marital = marital;
       this.military = military;
       this.language = language;
       this.socialAccount = socialAccount;
       this.school = school;
       this.gradProjIdea = gradProjIdea;
       this.projGrade = projGrade;
       this.certAqui = certAqui;
       this.postGradStud = postGradStud;
       this.acadimicInst = acadimicInst;
       this.cvpath = cvpath;
       this.schoolName = schoolName;
       this.comment = comment;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public PlatfromIntake getPlatfromIntake() {
        return this.platfromIntake;
    }
    
    public void setPlatfromIntake(PlatfromIntake platfromIntake) {
        this.platfromIntake = platfromIntake;
    }
    public Serializable getEnglishname() {
        return this.englishname;
    }
    
    public void setEnglishname(Serializable englishname) {
        this.englishname = englishname;
    }
    public Serializable getArabicname() {
        return this.arabicname;
    }
    
    public void setArabicname(Serializable arabicname) {
        this.arabicname = arabicname;
    }
    public Serializable getApplicationNo() {
        return this.applicationNo;
    }
    
    public void setApplicationNo(Serializable applicationNo) {
        this.applicationNo = applicationNo;
    }
    public Integer getFkUniversityFacultySpecializationId() {
        return this.fkUniversityFacultySpecializationId;
    }
    
    public void setFkUniversityFacultySpecializationId(Integer fkUniversityFacultySpecializationId) {
        this.fkUniversityFacultySpecializationId = fkUniversityFacultySpecializationId;
    }
    public Integer getFkFacultyId() {
        return this.fkFacultyId;
    }
    
    public void setFkFacultyId(Integer fkFacultyId) {
        this.fkFacultyId = fkFacultyId;
    }
    public Integer getFkSpecializationId() {
        return this.fkSpecializationId;
    }
    
    public void setFkSpecializationId(Integer fkSpecializationId) {
        this.fkSpecializationId = fkSpecializationId;
    }
    public Integer getFkGraduationGradeId() {
        return this.fkGraduationGradeId;
    }
    
    public void setFkGraduationGradeId(Integer fkGraduationGradeId) {
        this.fkGraduationGradeId = fkGraduationGradeId;
    }
    public Serializable getGraduationYear() {
        return this.graduationYear;
    }
    
    public void setGraduationYear(Serializable graduationYear) {
        this.graduationYear = graduationYear;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }
    public Serializable getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Serializable mobile) {
        this.mobile = mobile;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(Serializable barcode) {
        this.barcode = barcode;
    }
    public Integer getAccFlag() {
        return this.accFlag;
    }
    
    public void setAccFlag(Integer accFlag) {
        this.accFlag = accFlag;
    }
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }
    public Serializable getUserpwd() {
        return this.userpwd;
    }
    
    public void setUserpwd(Serializable userpwd) {
        this.userpwd = userpwd;
    }
    public Serializable getImagepath() {
        return this.imagepath;
    }
    
    public void setImagepath(Serializable imagepath) {
        this.imagepath = imagepath;
    }
    public Serializable getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(Serializable rejectReason) {
        this.rejectReason = rejectReason;
    }
    public Date getDateOb() {
        return this.dateOb;
    }
    
    public void setDateOb(Date dateOb) {
        this.dateOb = dateOb;
    }
    public Serializable getGender() {
        return this.gender;
    }
    
    public void setGender(Serializable gender) {
        this.gender = gender;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getIdno() {
        return this.idno;
    }
    
    public void setIdno(Serializable idno) {
        this.idno = idno;
    }
    public Serializable getGraduationGrade() {
        return this.graduationGrade;
    }
    
    public void setGraduationGrade(Serializable graduationGrade) {
        this.graduationGrade = graduationGrade;
    }
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
    public Integer getMarital() {
        return this.marital;
    }
    
    public void setMarital(Integer marital) {
        this.marital = marital;
    }
    public Integer getMilitary() {
        return this.military;
    }
    
    public void setMilitary(Integer military) {
        this.military = military;
    }
    public Integer getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Integer language) {
        this.language = language;
    }
    public Serializable getSocialAccount() {
        return this.socialAccount;
    }
    
    public void setSocialAccount(Serializable socialAccount) {
        this.socialAccount = socialAccount;
    }
    public Serializable getSchool() {
        return this.school;
    }
    
    public void setSchool(Serializable school) {
        this.school = school;
    }
    public Serializable getGradProjIdea() {
        return this.gradProjIdea;
    }
    
    public void setGradProjIdea(Serializable gradProjIdea) {
        this.gradProjIdea = gradProjIdea;
    }
    public Serializable getProjGrade() {
        return this.projGrade;
    }
    
    public void setProjGrade(Serializable projGrade) {
        this.projGrade = projGrade;
    }
    public Serializable getCertAqui() {
        return this.certAqui;
    }
    
    public void setCertAqui(Serializable certAqui) {
        this.certAqui = certAqui;
    }
    public Serializable getPostGradStud() {
        return this.postGradStud;
    }
    
    public void setPostGradStud(Serializable postGradStud) {
        this.postGradStud = postGradStud;
    }
    public Serializable getAcadimicInst() {
        return this.acadimicInst;
    }
    
    public void setAcadimicInst(Serializable acadimicInst) {
        this.acadimicInst = acadimicInst;
    }
    public Serializable getCvpath() {
        return this.cvpath;
    }
    
    public void setCvpath(Serializable cvpath) {
        this.cvpath = cvpath;
    }
    public Serializable getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(Serializable schoolName) {
        this.schoolName = schoolName;
    }
    public Serializable getComment() {
        return this.comment;
    }
    
    public void setComment(Serializable comment) {
        this.comment = comment;
    }




}


