package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SubTrack generated by hbm2java
 */
public class SubTrack  implements java.io.Serializable {


     private int subtrackId;
     private Serializable subtrackName;
     private Serializable code;
     private Set platfromIntakes = new HashSet(0);

    public SubTrack() {
    }

	
    public SubTrack(int subtrackId) {
        this.subtrackId = subtrackId;
    }
    public SubTrack(int subtrackId, Serializable subtrackName, Serializable code, Set platfromIntakes) {
       this.subtrackId = subtrackId;
       this.subtrackName = subtrackName;
       this.code = code;
       this.platfromIntakes = platfromIntakes;
    }
   
    public int getSubtrackId() {
        return this.subtrackId;
    }
    
    public void setSubtrackId(int subtrackId) {
        this.subtrackId = subtrackId;
    }
    public Serializable getSubtrackName() {
        return this.subtrackName;
    }
    
    public void setSubtrackName(Serializable subtrackName) {
        this.subtrackName = subtrackName;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Set getPlatfromIntakes() {
        return this.platfromIntakes;
    }
    
    public void setPlatfromIntakes(Set platfromIntakes) {
        this.platfromIntakes = platfromIntakes;
    }




}


