package bean;
// Generated May 20, 2017 7:06:35 PM by Hibernate Tools 4.3.1



/**
 * TrackManual generated by hbm2java
 */
public class TrackManual  implements java.io.Serializable {


     private int trackManualId;
     private CourseManual courseManual;
     private PlatfromIntake platfromIntake;
     private Boolean isElective;
     private Integer elecetiveGroupId;

    public TrackManual() {
    }

	
    public TrackManual(int trackManualId) {
        this.trackManualId = trackManualId;
    }
    public TrackManual(int trackManualId, CourseManual courseManual, PlatfromIntake platfromIntake, Boolean isElective, Integer elecetiveGroupId) {
       this.trackManualId = trackManualId;
       this.courseManual = courseManual;
       this.platfromIntake = platfromIntake;
       this.isElective = isElective;
       this.elecetiveGroupId = elecetiveGroupId;
    }
   
    public int getTrackManualId() {
        return this.trackManualId;
    }
    
    public void setTrackManualId(int trackManualId) {
        this.trackManualId = trackManualId;
    }
    public CourseManual getCourseManual() {
        return this.courseManual;
    }
    
    public void setCourseManual(CourseManual courseManual) {
        this.courseManual = courseManual;
    }
    public PlatfromIntake getPlatfromIntake() {
        return this.platfromIntake;
    }
    
    public void setPlatfromIntake(PlatfromIntake platfromIntake) {
        this.platfromIntake = platfromIntake;
    }
    public Boolean getIsElective() {
        return this.isElective;
    }
    
    public void setIsElective(Boolean isElective) {
        this.isElective = isElective;
    }
    public Integer getElecetiveGroupId() {
        return this.elecetiveGroupId;
    }
    
    public void setElecetiveGroupId(Integer elecetiveGroupId) {
        this.elecetiveGroupId = elecetiveGroupId;
    }




}


